# Generated by Django 5.2.5 on 2025-08-28 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DadosClimaticos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_registro', models.DateField(help_text='Data do registro climático', unique=True)),
                ('temperatura_media', models.FloatField(help_text='Temperatura média diária em graus Celsius')),
                ('precipitacao', models.FloatField(help_text='Total de precipitação diária em mm')),
                ('umidade', models.FloatField(help_text='Umidade relativa do ar média diária')),
            ],
            options={
                'verbose_name': 'Dado Climático',
                'verbose_name_plural': 'Dados Climáticos',
                'ordering': ['-data_registro'],
            },
        ),
        migrations.CreateModel(
            name='NotificacaoDoenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_notificacao', models.DateField(help_text='Data da notificação do caso')),
                ('doenca', models.CharField(help_text='Nome da doença (ex: Dengue, Chikungunya)', max_length=100)),
                ('regiao', models.CharField(help_text='Região/bairro onde o caso foi notificado', max_length=100)),
                ('sexo', models.CharField(blank=True, max_length=10, null=True)),
                ('faixa_etaria', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Notificação de Doença',
                'verbose_name_plural': 'Notificações de Doenças',
                'ordering': ['-data_notificacao'],
            },
        ),
    ]
